// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMDNaDFsf2EncaWY24elrNXAy7_3v7Eds',
    appId: '1:190881551433:web:2655325a73829ebd62db98',
    messagingSenderId: '190881551433',
    projectId: 'buseasy-c6b28',
    authDomain: 'buseasy-c6b28.firebaseapp.com',
    storageBucket: 'buseasy-c6b28.firebasestorage.app',
    measurementId: 'G-6EDH18QJY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0TbkGWe62lV_8qwwhwBOe8FU_7CmVYvE',
    appId: '1:190881551433:android:aba361bcba7602e462db98',
    messagingSenderId: '190881551433',
    projectId: 'buseasy-c6b28',
    storageBucket: 'buseasy-c6b28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG-KCEvnj9UxwYTd1GMkJ-AR7ZuEBkb98',
    appId: '1:190881551433:ios:210d3e25992f109a62db98',
    messagingSenderId: '190881551433',
    projectId: 'buseasy-c6b28',
    storageBucket: 'buseasy-c6b28.firebasestorage.app',
    iosClientId: '190881551433-3gbovt9ghp9e6vb11c7mung1422mi1f9.apps.googleusercontent.com',
    iosBundleId: 'com.example.busEasy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG-KCEvnj9UxwYTd1GMkJ-AR7ZuEBkb98',
    appId: '1:190881551433:ios:210d3e25992f109a62db98',
    messagingSenderId: '190881551433',
    projectId: 'buseasy-c6b28',
    storageBucket: 'buseasy-c6b28.firebasestorage.app',
    iosClientId: '190881551433-3gbovt9ghp9e6vb11c7mung1422mi1f9.apps.googleusercontent.com',
    iosBundleId: 'com.example.busEasy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMDNaDFsf2EncaWY24elrNXAy7_3v7Eds',
    appId: '1:190881551433:web:fd4dd09c79a2521862db98',
    messagingSenderId: '190881551433',
    projectId: 'buseasy-c6b28',
    authDomain: 'buseasy-c6b28.firebaseapp.com',
    storageBucket: 'buseasy-c6b28.firebasestorage.app',
    measurementId: 'G-FSV1RGVWZS',
  );

}